stages:
  select_region:
    cmd: poetry run select_region data_dvc/raw/initial.json data_dvc/interim/initial.csv
    deps:
    - data_dvc/raw/initial.json
    outs:
    - data_dvc/interim/initial.csv

  clean_data:
    cmd: poetry run clean_data data_dvc/interim/initial.csv data_dvc/interim/cleaned.csv
    deps:
    - data_dvc/interim/initial.csv
    outs:
    - data_dvc/interim/cleaned.csv

  add_features:
    cmd: poetry run add_features data_dvc/interim/cleaned.csv data_dvc/processed/featured.csv
    deps:
    - data_dvc/interim/cleaned.csv
    outs:
    - data_dvc/processed/featured.csv
